version: '3.8'

services:
  livekit-server:
    image: hariszaki17/livekit:server-latest
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
    command: ["--bind", "0.0.0.0"]

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
